task 1 CLI
ekaterinaMaljutina/Software-Design pull request #1
Opened 2017-02-25 21:35 UTC by ekaterinaMaljutina

2017-02-26 13:18 UTC, yurii-litvinov requested changes
Ещё бы диаграмму неплохо бы

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Cat.java
> +public class Cat implements Command {
Самим классам тоже нужен комментарий, с точки зрения архитектуры это даже важнее, чем комментарии к методам. Про каждый класс должно быть можно сказать, для чего он предназначен (а если учесть принцип единственности ответственности, то это должно быть можно сказать в одном предложении), и это лучше явно написать в коде. Даже если это очевидно из названия класса.

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Cat.java
> +    public Environment run(Environment state, String[] args, Printed printed) throws Exception{
По джавовскому стайлгайду перед фигурными скобками ставится пробел, не могу не придраться :)

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Cat.java
> +            args = new String[]{Environment.fileName};
А тело if-ов, for-ов и т.д. все рекомендуют помещать в фигурные скобки даже если там всего один оператор, чтобы избежать фэйлов в духе
```java
if (args.length == 0)
    System.out.println("args.length is 0");
    args = new String[]{Environment.fileName};
```

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Cat.java
> +        for (String fileName : args){
Тут и ниже тоже проверьте на пробелы перед фигурными скобками, пожалуйста. Стайлгайд --- это святое

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Cat.java
> +                if (printed .equals(Printed.YES)) {
А вот перед точкой пробел лишний

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Cat.java
> +        InputStream inputStream = new FileInputStream(file);
Лучше try-with-resources (https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html), меня такой код пугает --- а вдруг исключение?

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Command.java
> +public interface Command {
И интерфейсам тоже нужны комментарии, причём, поскольку интерфейсы имеют большее влияние на архитектуру, комментарии к ним даже важнее, чем к классам

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Command.java
> +    public enum Printed{ YES, NO }
Это как-то некрасиво с архитектурной точки зрения --- каждая команда должна что-то делать или не делать в зависимости от того, выводить ей на консоль или нет. Проще было бы команде вообще ничего не знать про консоль, а просто читать данные из входного потока и выводить в выходной, при этом сам шелл бы решал, что делать с содержимым потоком --- печатать или нет.

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Command.java
> +     * @return
Пустые JavaDoc-тэги --- это плохо, даже хуже, чем если бы их вообще не было :)

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Environment.java
> +    public static final String fileName = "enviroment.txt";
И даже для такой штуки нужен комментарий

2017-02-26 13:18 UTC, yurii-litvinov commented on README.md
> +Класс, хрянящив в себе (в виде файла) перенаправленный поток ввода/вывода, для того, чтобы можно было передавать информацию через пайп.
Как-то не очень убедительно. Зачем хранить поток ввода-вывода в файле, почему не в памяти?

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Parser.java
> +        if (command.indexOf("'")>=0 && command.lastIndexOf("'") > command.indexOf("'")) {
`command.indexOf("'")>=0` я бы писал как `command.indexOf("'") >= 0`

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Parser.java
> +        return false;
`if (...) return true else return false;` --- это всё равно, что `if (... == 0) return 0 else if (... == 1) return 1 else if (... === 2) ...`.
Булевые выражения --- это обычные выражения, возвращающие значения, так что проще было бы писать сразу `return command.indexOf("'") >= 0 && command.lastIndexOf("'") > command.indexOf("'")`

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Parser.java
> +    public static String removeDuplicSpaces(String str){
Лучше не сокращать имена методов, это читабельность ухудшает

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/PreProcess.java
> +
Мне кажется, лишняя пустая строчка

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/PreProcess.java
> +
И вообще, две пустые строки подряд обычно не поощряются стайлгайдами

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/PreProcess.java
> +        while(idx >= 0){
Между ключевым словом и `(` тоже ставится пробел

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/PreProcess.java
> +                if (idxNext - idx < 0 ) {
А вот перед `)` --- не ставится

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/PreProcess.java
> +            str = str.substring(0, idx) + variable.get(str.substring(idx+1, idxNext)) + str.substring(idxNext);
`idx+1` --- ну Вы поняли :)

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Pwd.java
> +        if (printed.equals( Printed.YES)) {
И тут лишний пробел

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/RunCommand.java
> +public class RunCommand {
Вот это какая-то сильно умная штука, что не очень хорошо с точки зрения принципа единственности ответственности, декомпозиции и переиспользования. Создание и исполнение команд можно было бы разделить, например, и вынести после этого создание команд в отдельный класс (паттерн "Фабрика", который мы ещё не проходили) :) Это бы, кстати, позволило сначала создать команды, потом связать их потоки ввода-вывода, а потом все сразу исполнить.

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/RunCommand.java
> +                System.exit(1);
А почему "1"? Выход по команде `exit` же вполне корректен.

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Wc.java
> +            wordsCount = 0;
Лучше каждой переменной своё объявление, так более читаемо

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/Cat.java
> +import java.io.File;
По-хорошему, каждый класс должен быть в своём пакете. Пакеты --- это мощная штука для иерархической декомпозиции программы, в хоть сколько-нибудь крупных программах без них никуда. У Вас, например, очевидно, есть команды, парсер/препроцессор и "обвязка" --- логически обособленные куски программы, хорошие кандидаты на пакеты. Но даже если нет, то лучше всё хранить в одном именованном пакете, а не в пакете по умолчанию.

2017-02-26 13:18 UTC, yurii-litvinov commented on src/main/java/PreProcess.java
> +                variable.put(fileWithVariable.next(), fileWithVariable.next());
У меня здесь падают тесты с java.util.NoSuchElementException

2017-02-26 13:49 UTC, ekaterinaMaljutina commented on src/main/java/PreProcess.java
> +                variable.put(fileWithVariable.next(), fileWithVariable.next());
А с какой командой падает?

2017-02-26 14:21 UTC, yurii-litvinov commented on src/main/java/PreProcess.java
> +                variable.put(fileWithVariable.next(), fileWithVariable.next());
Со всеми, и при запуске консоли при инициализации. Под виндой

2017-03-01 13:16 UTC, yurii-litvinov requested changes
Диаграмма лучше, чем ничего, но на ней ещё можно отобразить, кто кого включает, создаёт и использует, было бы более полезно. Сейчас это можно не править, как "пройдём" UML, вернёмся к этому.

2017-03-01 13:16 UTC, yurii-litvinov commented on README.md
> +	- **Exit**
Граммар-наци негодует :)

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/commandCreator/CommandCreate.java
> +                throw new Exception("command name not found");
Более идеологически правильно было бы сделать свой класс-исключение и кидать его. Так мы можем случайно поймать и обработать исключение, которое не является "command name not found" и пропустить другую ошибку в программе. Вообще, исключения должны быть по максимуму специфичны, и ловить (и декларировать в throws) надо возможно более узкое подмножество исключений, именно чтобы не ловить не по делу "неожиданные" исключения.

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/RunCommand.java
> +        return commandCreatorFactory.create();
Тут, судя по всему, используется фабрика фабрик, чтобы получить фабрику, которая создаст нам команду --- а чем это лучше просто фабрики команд? :)

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/RunCommand.java
> +    private boolean setEnvitonmentVariable(String command) {
Тоже граммар-наци негодует :) setEnvi**r**onmentVariable

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/RunCommand.java
> +        return parseCommand;
Parser, я думаю, вполне сам бы мог справиться с разбором, тут RunCommand пытается каким-то микроменеджментом заниматься.

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/RunCommand.java
> +public class RunCommand {
Вообще, принято, чтобы каждый класс был в своём пакете. Заводится корневой пакет для всего проекта (обычно в форме записанного в обратную сторону доменного имени организации, типа ru.spbau.mit, плюс идентификатор конкретного проекта, типа для глобальной уникальности имен пакетов) и все классы кладутся либо в него, либо в его подпакеты. https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/RunCommand.java
> +            }
Так не работают штуки наподобие `echo 'aaa' "$x"`. По-хорошему, надо гнать препроцессирование всегда, и оно должно само разбираться с квотированием

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/RunCommand.java
> +    }
С архитектурной точки зрения я бы предпочёл чётко разделить фазы препроцессирования, парсинга и исполнения команд, концепция "разбили по пайпам и каждую часть пытаемся распарсить и исполнить отдельно" тоже валидна, но приводит к излишней переплетённости разных кусков кода. Тут постоянно дёргается то препроцессор, то парсер, то исполнение команды, то снова парсер, за этим тяжело уследить. В компиляторах есть уже некая устоявшаяся архитектура --- препроцессор -> лексер -> парсер -> интерпретатор, было бы лучше ей следовать. Но, как я говорил на паре, архитектура --- дело довольно-таки гуманитарное, так что сказать "у вас неправильно" нельзя, а "мне не нравится, переделайте" как-то не очень :)
Можно так и оставить.

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/Shell.java
> +public class Shell {
Нужен комментарий

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/Shell.java
> +        RunCommand runCommaner = new RunCommand();
runCommaner --- тоже какое-то странное имя :)

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/command/Cat.java
> +            inputStream.close();
Это лучше делать через try-with-resources: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html. Иначе любое исключение заставит эту штуку оставить файл открытым

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/command/Cat.java
> +            System.exit(1);
Не, если пользователь опечатался в имени файла, лучше просто не исполнить команду, а не выходить из шелла вообще

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/command/Command.java
> +public abstract class Command {
Кажется, он мог бы быть интерфейсом

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/command/Wc.java
> +            throw new Exception("no filename in args");
Исключение --- это хорошо, то, что после него шелл закрывается --- плохо, надо дать возможность продолжить работу.

2017-03-01 13:16 UTC, yurii-litvinov commented on src/main/java/parser/Parser.java
> +public class Parser {
И даже тут нужен комментарий

2017-03-02 22:05 UTC, yurii-litvinov approved these changes
В общем, остались только мелочи, так что зачтена

2017-03-02 22:05 UTC, yurii-litvinov commented on gradlew
> +# Determine the Java ru.spbau.mit.command to use to start the JVM.
Автозамена разгулялась

2017-03-02 22:05 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/CommandInvoker.java
> +import com.sun.istack.internal.NotNull;
Точно не org.jetbrains.annotations.NotNull?

2017-03-02 22:05 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/CommandInvoker.java
> +     * Get ru.spbau.mit.command by name
Автозамена ужасна

2017-03-02 22:05 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/CommandInvoker.java
> +                System.out.println("not ru.spbau.mit.command name");
:)

2017-03-27 19:06 UTC, merged