Books store Task 3
ekaterinaMaljutina/Software-Design pull request #3
Opened 2017-03-27 21:42 UTC by ekaterinaMaljutina

2017-04-29 20:50 UTC, yurii-litvinov requested changes
По диаграмме:
- Почти все связи --- зависимости `<<use>>`, что, в принципе, ок, но недостаточно детально. От модели предметной области ожидается что-то, похожее на схему БД --- кто на кого ссылается, кто кого содержит, множественности для случаев, когда они отличаются от 1. Например, связь между корзиной и книгой на диаграмме не очевидна, а ведь основная задача модели --- визуализировать отношения сущностей из реального мира.
- Ещё кто такой WishList неочевидно. Вообще, может быть, вся магия происходит в методах, но их логика на диаграмме не рисуется, поэтому диаграмма не очень полезна. Имеет смысл по возможности заменить методы на поля и отношения между классами (например, getWishList на отношение с Book с именем роли wishList и множественностью *). А вот, например, `pay` --- это действие, реально имеющее место в предметной области, его убирать не надо.
- Хотелось уметь оплачивать картой или по счёту, а по диаграмме кажется, что можно только картой
- User использует интерфейс Person, или реализует его?
- ReviewModerator, если его наследовать от User, будет вынужден иметь bankAccount. Что может быть и неплохо, но опять-таки, кажется преждевременным решением, которое из самой предметной области не следует.
- Чисто синтаксически, между классами и enum-ами отношение обычно не рисуется, enum-ы изображаются просто как поля
- Круговая зависимость между Basket и Session --- это с архитектурной точки зрения плохо
- Вообще, неплохо бы навести какую-то иерархическую структуру, чтобы было видно, кто кем пользуется. Ну, насколько это возможно.

2017-04-29 20:50 UTC, yurii-litvinov commented on book-store/README.md
> +    * Использовать плаженый API сервис. Paypal
Paypal --- это скорее деталь реализации, при анализе предметной области надо избегать таких (возможно, преждевременных) решений

2017-04-29 20:50 UTC, yurii-litvinov commented on book-store/README.md
> +		* Создадим в СУБД новые страницы для создания новых отзывов
мм, страницы в СУБД?

2017-05-18 06:37 UTC, yurii-litvinov requested changes
* Непонятно, кто вызывает PayController. Он пользуется заказом или заказ им?
* А зачем разделять User и Client?
* Между классами и enum-ами отношение обычно не рисуется, например, между OrderBook и OrderStatus
* ReviewController правда наследуется от Review? Выглядит оно так, будто хранит в себе ревью для книг и возвращает по запросу, лучше сделать его отдельным классом.
* Moderator как-то связан с OrderReturn?
* Также непонятно, как Searcher использует ExterAPI, он же просто ищет книги. Или имелось в виду наоборот?
* BookCatagory --- опечатка

В общем, почти всё ок, но проверьте все зависимости, там либо лишние есть, либо требующие пояснения (либо комментарием, либо укажите в зависимом классе метод, который бы вызывался зависящим от него классом). Доисправляйте, пожалуйста. И не надо всю диаграмму переделывать :)

2017-05-18 14:17 UTC, ekaterinaMaljutina commented
Вроде бы все замечания поправила.

2017-05-30 07:28 UTC, yurii-litvinov commented
Теперь OrderBook и OrderStatus вообще никак не связаны :) По-хорошему, надо было убрать ассоциацию, но добавить в OrderBook поле типа OrderStatus. В остальном всё ок, зачтена

2017-05-30 09:10 UTC, yurii-litvinov approved these changes

2017-05-30 18:00 UTC, merged